# "test" checks if the file/profile/bashrc exists usinf '-f'
# and if file exists then runs the next command
# Example:
# generated by Git for Windows
# test -f ~/.profile && . ~/.profile

bashrc_path="~/.bashrc"
test -f $bashrc_path && . $bashrc_path
