# "test" checks if the file/profile/bashrc exists usinf '-f'
# and if file exists then runs the next command
# Example:
# generated by Git for Windows
# test -f ~/.profile && . ~/.profile

test -f ~/.bashrc && . ~/.bashrc
